baseURL = 'https://yoloinfinity55.github.io/'
languageCode = 'en-us'
title = 'YOLO Infinity 55 Blog'

[params]
  homeInfoParams = { Title = "Welcome to YOLO Infinity 55!", Content = "Hi, I'm yoloinfinity55! This is my personal blog where I share my adventures, projects, and thoughts on tech and creativity. Explore my latest posts below or check out my GitHub for more!", Image = "/images/home-banner.jpg", ImagePosition = "right", ImageWidth = "300px" }
  socialIcons = [
    { name = "github", url = "https://github.com/yoloinfinity55" },
    { name = "twitter", url = "https://x.com/yoloinfinity55" }
  ]
  ShowReadingTime = true
  ShowWordCount = true
  ShowBreadcrumbs = true
  ShowPostNavLinks = true
  ShowAllPagesOnHome = true
  ShowTaxonomyPostCount = true
  ShowCoverImageInList = true
  ShowCoverImageInSingle = true
  Paginate = 5
  PaginatePath = "page"
  customCSS = ["posts-grid.css", "homepage.css"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"