baseURL = 'https://yoloinfinity55.github.io/'
languageCode = 'en-us'
title = 'YOLO Infinity 55 Blog'


[params]
  homeInfoParams = { Title = "Welcome to YOLO Infinity 55", Content = "This is my personal blog where I share my thoughts, projects, and adventures!" }
  socialIcons = [
    { name = "github", url = "https://github.com/yoloinfinity55" }
  ]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"